### ISSUE TITLE
any example 

### ISSUE THREAD

**Issue by jjqcat** [lammertb/libfins#11] opened 2020-11-28 16:05 UTC
Hi, I need one simple example to show how to call  these functions when using , thanks

**Comment by jjqcat** [comment] 2021-02-06 13:42
I can't use this library communicate with fins server...  would you give me examples?

**Comment by jjqcat** [comment] 2021-02-06 16:00
struct fins_cpudata_tp cpudata;
	finslib_cpu_unit_data_read((fins_sys_tp*)_fins,&cpudata);

        after connected to PLC server, this function call return error

**Comment by lammertb** [comment] 2021-02-06 19:34
Without context (TCP/UDP), type of PLC, the commands to open the connection, error code, etc, it is guessing what is going wrong.

In general, it is a bad idea to use type casts in function calls because it disables the type checking logic of the compiler. Better is to use `finslib_cpu_unit_data_read(_fins,&cpudata);` If the compiler complains with this function call, the _fins parameter has probably the wrong type.

**Comment by jjqcat** [comment] 2021-02-07 03:50
Oh, after call finslib_tcp_connect succeeded, then  failed to call finslib_cpu_unit_data_read

**Comment by jjqcat** [comment] 2021-02-09 12:36
the function finslib_tcp_connect return FINS_RETVAL_CLOSED_BY_REMOTE error, I don't know what's reason.

**Comment by lammertb** [comment] 2021-02-09 19:52
Which PLC model do you try to connect to? I will see if I have a comparable device here and create a piece of working example code.

**Comment by jjqcat** [comment] 2021-02-11 02:50
I use one OMRON Fins virtual server,    set plc_mode=2 and it works well.

**Comment by lammertb** [comment] 2021-02-11 08:04
Well, it looks like your issue is a hardware issue then, not a software issue.  Hardware support is available as a paid service, not as a free service through github. I will close this issue now as being not a bug.

**Closed by lammertb** 2021-02-11 08:04 UTC
Labels: Not a bug
